# -*- coding: utf-8 -*-
apiVersion: v1
kind: Service
metadata:
  name: mef-cache
spec:
  type: NodePort
  ports:
    - port: 6379
      nodePort: 30065
      name: cache
  selector:
    app: mef
    tier: cache
---
apiVersion: v1
kind: Service
metadata:
  name: mef-db
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 30064
      name: db
  selector:
    app: mef
    tier: db
---
apiVersion: v1
kind: Service
metadata:
  name: mef-indexer
spec:
  type: NodePort
  ports:
    - port: 9200
      nodePort: 30062
      name: api
    - port: 9300
      nodePort: 30063
      name: cluster
  selector:
    app: mef
    tier: indexer
---
apiVersion: v1
kind: Service
metadata:
  name: mef-mq
spec:
  type: NodePort
  ports:
    - port: 5672
      nodePort: 30067
      name: worker
    - port: 15672
      nodePort: 30066
      name: ui
  selector:
    app: mef
    tier: mq
---
apiVersion: v1
kind: Service
metadata:
  name: mef-tasksui
spec:
  type: NodePort
  ports:
    - port: 5555
      nodePort: 30068
  selector:
    app: mef
    tier: tasksui
---
apiVersion: v1
kind: Service
metadata:
  name: mef-frontend
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30060
      name: http
    - port: 443
      nodePort: 30061
      name: https
  selector:
    app: mef
    tier: frontend
