# -*- coding: utf-8 -*-
kind: Pod
apiVersion: v1
metadata:
  name: init-data
spec:
  restartPolicy: Never
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: mef-claim-data
  containers:
  - name: copy-data
    image: ubuntu
    command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
    volumeMounts:
    - name: vol
      mountPath: /claim
