# -*- coding: utf-8 -*-

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mef-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mef
        tier: db
    spec:
      containers:
      - name: mef-db
        image: postgres:11
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: mef
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: mef
              key: POSTGRES_DB
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mef
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
          name: db
        volumeMounts:
          - mountPath: /var/lib/postgresql
            name: mef-db-data
      volumes:
      - name: mef-db-data
        persistentVolumeClaim:
          claimName: mef-claim-db
