#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# RERO MEF
# Copyright (C) 2020 RERO
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

NC='\033[0m'                    # Default color
INFO_COLOR='\033[1;97;44m'      # Bold + white + blue background
SUCCESS_COLOR='\033[1;97;42m'   # Bold + white + green background
ERROR_COLOR='\033[1;97;41m'     # Bold + white + red background

PROGRAM=`basename $0`

set -e

# MESSAGES
msg() {
  echo -e "${1}" 1>&2
}
# Display a colored message
# More info: https://misc.flogisoft.com/bash/tip_colors_and_formatting
# $1: choosen color
# $2: title
# $3: the message
colored_msg() {
  msg "${1}[${2}]: ${3}${NC}"
}

info_msg() {
  colored_msg "${INFO_COLOR}" "INFO" "${1}"
}

error_msg() {
  colored_msg "${ERROR_COLOR}" "ERROR" "${1}"
}

error_msg+exit() {
    error_msg "${1}" && exit 1
}

success_msg() {
  colored_msg "${SUCCESS_COLOR}" "SUCCESS" "${1}"
}

set -e

# Displays program name
msg "PROGRAM: ${PROGRAM}"

if ! options=$(getopt -o dsb -l -t deploy,ci -- "$@")
then
    # something went wrong, getopt will put out an error message for us
    exit 1
fi

# The real bootstrap script starts 20 lines below ;-)
flags=()
deploy=false
cmd="poetry install"
ci=false
while test $# -gt 0
do
    case "$1" in
      -d|--deploy)
        # We are probably inside travis, check for env variables
        deploy=true ;;
      -c|--ci)
        # We are probably inside travis, check for env variables
        ci=true ;;
      (--) shift; break;;
      (-*) flags+=("$1") ;;
      (*) break;;
    esac
    shift
done

# Poetry is a mandatory condition to launch this program!
if [[ -z "${VIRTUAL_ENV}" ]]; then
  error_msg+exit "Error - Launch this script via poetry command:\n\tpoetry run ${PROGRAM}"
fi

if $deploy ; then
  if ! $ci ; then
      flags=("--no-dev")
  fi
fi

if ! $deploy ; then
    if $ci ; then
        cmd="poetry update"
    fi
fi

poetry --version

# create virtualenv and upgrade pip
info_msg "Upgrade pip"
poetry run pip install --upgrade pip

info_msg "Install poethepoet"
poetry run pip install poethepoet

# install the application and all the dependencies
info_msg "Install with command: ${cmd} ${flags[@]}"
${cmd} ${flags[@]}

# install the app itself
if ! $deploy ; then
    if $ci ; then
        poetry install
    fi
fi

# build the web assets
info_msg "Build web assets: collect"
invenio collect -v

info_msg "Build web assets: using webpack for invenio-admin"
invenio webpack buildall

if $deploy ; then
  if ! $ci ; then
    info_msg "Clean web assets"
    invenio webpack clean

    info_msg "Clean npm cache"
    npm cache clean --force

    info_msg "Clean pip cache"
    pip cache purge
  fi
fi

success_msg "${PROGRAM} finished!"
exit 0
