#!/usr/bin/env bash
# SPDX-FileCopyrightText: Fondation RERO+
# SPDX-License-Identifier: AGPL-3.0-or-later

PROGRAM=`basename $0`

set -e

# Colored message helpers: msg, info_msg, error_msg, error_msg+exit,
# success_msg, colored_msg.
. "$(dirname "${BASH_SOURCE[0]}")/messages"

# Displays program name
msg "PROGRAM: ${PROGRAM}"

if ! options=$(getopt -o ds -l -t deploy,ci -- "$@")
then
    # something went wrong, getopt will put out an error message for us
    exit 1
fi

# The real bootstrap script starts 20 lines below ;-)
flags=()
deploy=false
cmd="uv sync --frozen"
ci=false
while test $# -gt 0
do
    case "$1" in
      -d|--deploy)
        # We are probably inside travis, check for env variables
        deploy=true ;;
      -c|--ci)
        # We are probably inside travis, check for env variables
        ci=true ;;
      (--) shift; break;;
      (-*) flags+=("$1") ;;
      (*) break;;
    esac
    shift
done

# uv is a mandatory condition to launch this program!
if [[ -z "${VIRTUAL_ENV}" ]]; then
  error_msg+exit "Error - Launch this script via uv command:\n\tuv run ${PROGRAM}"
fi

if $deploy ; then
  if ! $ci ; then
      flags=( "--no-group dev --group prod" )
  fi
else
    if $ci ; then
        cmd="uv sync --upgrade"
    fi
fi

# BOOTSTRAP START
# install the application and all the dependencies
flag="${flags[@]}"
info_msg "Install with command: ${cmd} ${flag}"
${cmd} ${flags[@]}

# build the web assets
info_msg "Build web assets: collect"
invenio collect -v

info_msg "Build web assets: using webpack for invenio-admin"
invenio webpack buildall

if $deploy ; then
  if ! $ci ; then
    info_msg "Clean web assets"
    invenio webpack clean

    info_msg "Clean npm cache"
    npm cache clean --force

    info_msg "Clean pip cache"
    pip cache purge
  fi
fi

success_msg "${PROGRAM} finished!"
exit 0
