#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# This file is part of RERO MEF.
# Copyright (C) 2018 RERO.
#
# RERO MEF is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# RERO MEF is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with RERO MEF; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, RERO does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.

set -e

data_path=$(pipenv --where)/data

# Clean redis
pipenv run invenio shell --no-term-title -c "import redis; redis.StrictRedis.from_url(app.config['CACHE_REDIS_URL']).flushall(); print('Cache cleared')"
pipenv run invenio db destroy --yes-i-know
pipenv run invenio db init create
pipenv run invenio index destroy --force --yes-i-know
pipenv run invenio index init --force
pipenv run invenio index queue init purge

# Create admin role to rectict access
pipenv run invenio roles create admin
pipenv run invenio access allow superuser-access role admin


RED='\033[0;31m'
GREEN='\033[0;0;32m'
NC='\033[0m' # No Color
# import the records
for SOURCE in bnf gnd rero viaf mef
do
    echo -e ${GREEN}Importing ${SOURCE} records:${NC}
    pipenv run dojson -i ${data_path}/${SOURCE}.json schema http://mef.test.rero.ch/schemas/authorities/${SOURCE}-person-v0.0.1.json | pipenv run invenio records create --pid-minter ${SOURCE}
    pipenv run invenio index reindex --yes-i-know --pid-type ${SOURCE}
done
pipenv run invenio index run -c 4
