name: build
on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependencies: ['development', 'deploy']
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Docker compose up
      run: docker-compose up -d

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Bootstrap
      if: ${{ matrix.dependencies == 'development' }}
      run: |
        poetry run ./scripts/bootstrap --ci
        pip install --upgrade coveralls

    - name: Bootstrap deploy
      if: ${{ matrix.dependencies == 'deploy' }}
      run: |
        poetry run ./scripts/bootstrap --ci --deploy E2E=yes

    - name: Run Test
      run: poetry run poe run_tests

    - name: Coveralls
      if: ${{ matrix.dependencies == 'development' }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_SERVICE_NAME: github
      run: |
          coveralls