
# RERO MEF
# Copyright (C) 2025 RERO.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

on:
  push:
    branches: [staging]
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
        dependencies: ['dev', 'deploy']
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.13.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v6

    - name: Setup node
      uses: actions/setup-node@v6
      with:
        node-version: '18'

    - name: Docker compose up
      run: docker compose up -d

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        cache-dependency-glob: uv.lock

    - name: Set up Python
      run: uv python install ${{ matrix.python-version }}

    - name: Bootstrap
      if: ${{ matrix.dependencies == 'dev' }}
      run: |
        uv run ./scripts/bootstrap --ci

    - name: Bootstrap deploy
      if: ${{ matrix.dependencies == 'deploy' }}
      run: |
        uv run ./scripts/bootstrap --ci --deploy E2E=yes

    - name: Run Test
      run: uv run poe run_tests
      env:
        RERO_MEF_COVERAGE: ${{ matrix.dependencies == 'dev'}}

    - name: Coveralls
      if: ${{ matrix.dependencies == 'dev'}}
      uses: coverallsapp/github-action@v2
      with:
        format: cobertura
        file: ./coverage.xml
        github-token: ${{ secrets.GITHUB_TOKEN }}
